/* Interface outline: implementation bodies removed. */
import { S } from '../state.js';

function sessionModeBadge(mode, sessionType);
function formatRemainingShort(ms);
function sessionAvatarHtml(partner, cls = 'chat-avatar');
function lastMsgText(lm);
function sessionRowHtml(s);
function renderSessions();
function startSessionCountdown();
function stopSessionCountdown();
async function loadSessions();
async function checkRefundOnSessions();
function openSession(session);
function openSessionById(matchId);
function renderChatHeaderActions();
function applyChatBackground();
async function editChatWallpaper();
function setChatActionButtonsDisabled(disabled);
async function confirmRelationship(matchId);
function syncOpenSessionFromList(matchId);
async function dissolveRelationship(matchId);
function refundBannerText(meta);
function showRefundBanner(notif);
async function refreshEnergyBalance();
function isChatDissolved();
async function openChat(...);
function openChatPartnerProfile();
function closeChat();
function applyChatComposerState();
async function loadChatHistory();
function attrEscape(v);
function avatarHtml(mine);
function openChatAvatarMenu(ev);
async function chatNudge();
function formatChatStamp(iso);
function timeSepHtml(iso);
function messageHtml(m, myId);
function chatStreamHtml(msgs, myId, prevIso);
function renderChatMessages(stickToBottom = true);
function appendChatMessages(msgs, prevMsg);
function loadEarlierChatMessages();
function bindChatScrollHandler();
function appendOwnMessage(msg);
function handleChatSendError(e, fallback);
async function sendChatMessage();
function onChatImagePicked(input);
function clearChatPendingImage();
function restoreChatPendingImage(file);
async function sendChatImage(file);
function openChatImage(url);
async function markChatRead();
function markRowRead(id);
async function refreshReadReceipts();
async function pollChatMessages();
function startChatPolling();
function stopChatPolling();
