/* Interface outline: implementation bodies removed. */
import { S } from '../state.js';

function normalizeGrade(raw);
async function fetchMetadata(path);
function fillMetaSelect(id, items, current, placeholder);
function setupWizardGo(i);
function setupWizardValidate(i);
function setupWizardNext();
function setupWizardPrev();
function setupWizardReset();
async function initProfileSetupPage();
function addSetupTag();
function addSetupTagValue(tag);
function removeSetupTag(i);
function getSetupTags();
function renderSetupTags();
function selectYear(el);
function selectSetupSegment(el, groupClass);
function selectSetupGender(el);
function selectSetupGenderPref(el);
function fillSetupBirthday(p);
function ageFromBirthday(birthday);
async function saveProfile();
async function handleAvatarFile(event, target = 'setup');
async function loadProfileTab();
function renderVerifyButton();
function openVerify();
function closeVerify();
async function handleStudentCardFile(event);
async function sendVerifyCode();
async function submitVerification();
function setupBgPullReveal();
async function openEditProfile();
function closeEditProfile();
async function saveEditProfile();
function openEditHomepage();
function closeEditHomepage();
async function saveEditHomepage();
function renderEditTags();
function openAddInterest();
function closeAddInterest();
function addInterestValue(tag);
function confirmAddInterest();
function removeEditTag(i);
function triggerCoverUpload();
async function handleCoverFile(event);
function getStoredPhotos();
async function saveStoredPhotos(p);
function renderProfilePhotosStrip();
function renderPhotoSlots();
function triggerProfilePhotoUpload();
async function removeProfilePhoto(i);
function openPreview();
function closePreview();
function renderPreviewPage();
function renderPublicProfileCard(...);
function selectGenderSegment(val);
function updateGenderUI();
function updateAgeDisplay();
function onAgeMinInput();
function onAgeMaxInput();
function savePreferences();
function renderEnergyDisplay();
async function loadEnergyBar();
async function loadEnergyPackages();
function openEnergyModal();
function closeEnergyModal();
function highlightEnergyPackage(el);
function updateEnergyPayButton();
function selectEnergyPackage(pkgId, el);
function highlightPayMethod(el);
function selectPaymentMethod(method, el);
async function confirmEnergyPurchase();
async function claimEnergy(claimType);
function openTickets();
async function loadMyTickets();
function openTicketDetail(i);
function closeTicketDetail();
async function addTicketToWallet(ticketId);
