/* Interface outline: implementation bodies removed. */
import { S } from '../state.js';
import { fetchSquareAds, adLargeCard, observeAdImpressions } from './ads.js';

function isOfficial(p);
function feedEl(tab);
function trackEl();
function pagerWidth();
function trackOffset(tab);
function setTrack(x, animate);
async function loadSquareTab();
function positionSquareInk();
function switchSquareTab(el, tab);
function bindSquareSwipe();
function unwrap(data);
function onSquareSearch(text);
function toggleSquareSearch(force);
function syncSearchPadding();
function runSquareSearch();
function clearSquareSearch();
function bindFabDrag();
async function loadSquareTab2(tabArg);
function renderSquareNeedSchool(tab);
function renderSquareFeed(posts, ads = [], tab);
function scheduleMasonry();
function layoutSquareMasonry();
function observeMasonryItems();
function postAuthorDisplay(p);
function postAuthorName(p);
function schoolBadge(p);
function officialBadge(p);
function avatarChip(profile, fallbackName, sizeClass, textSize, extra);
function renderAuthorAvatars(post);
function clampStyle(lines);
function pollBlock(p);
async function votePollOption(postId, optionIndex);
function eventPrice(ev);
function eventTimeShort(iso);
function eventStrip(p);
function eventDetailBlock(p);
async function buyEventTicket(eventId);
function postLikeButton(p);
function cardAuthorRow(p);
function renderSearchPeople();
function commentSnippetLine(p);
function bentoTextCard(p);
function bentoLargeCard(p);
function pastelBg(seed);
function bentoSmallCard(p);
function bentoWideCard(p);
function applyLikeButtonState(btn, liked, count);
async function likePost(postId, btn);
function syncPostLikeState(postId, liked, likeCount);
function patchSquareCard(...);
async function openPostDetail(postId, focusComposer = false);
function focusPdComposer();
async function askReportReason(titleZh, titleEn);
function reportDoneToast(err);
function openPdPostMenu(ev);
async function sharePdPost();
async function reportPdPost();
function pdCommentText(commentId);
async function reportPdComment(commentId);
function applyPdCommentLike(commentId, liked, likeCount);
function findPdComment(commentId);
async function likePdComment(commentId, btn);
async function sharePdComment(commentId);
function openPdCommentMenu(commentId, x, y);
function bindPdCommentLongPress();
function closePostDetail();
async function loadPostDetail(postId);
function syncPostDetailToList(post);
function renderPdImages(images);
function pdCarouselNav(dir);
function pdCarouselScrolled(el);
function renderPdComment(cm, replyTargetId, isReply, authorKey);
function renderPostDetail(post);
function setPdReply(commentId, replyTargetId);
function cancelPdReply();
async function submitPdComment();
async function likePdPost();
function openNewPost();
function renderPollOptionInputs(count);
function addPollOptionInput();
function toggleNewPostPoll(checked);
function selectNewPostBoard(board);
function syncNewPostBoardUI();
function toggleNewPostAnonymous(checked);
function closeNewPostForm();
function handlePostImages(e);
function removeNewPostImage(idx);
function renderNewPostImages();
async function submitNewPost();
function formatPostTime(iso);
